### PR TITLE
src : add setTerritory() to api/Fetcher.js so all fetchers can set for Territory

### PR DESCRIPTION
**Pull request by ghost**
When i using  chartFetcher.fetchCharts() to get the chart data, i found that i could only get TW chart data as default.  
According to the [api doc](https://docs-en.kkbox.codes/v1.1/reference#charts_1), i could set the territory code but if i want to get the data from "JP"、"HK", it seems that i cant do it. Maybe there may be a way to set Territory.  

origin example code 
`chartFetcher.fetchCharts().then(response => {   
  console.log(response.data)
})`  
   
So i add a setTerritory() in ChartFetcher.js for setting the constructor territory value instead of "TW" if people want to fetch other country chart data.    

pull request example code 
` chartFetcher.setTerritory("JP").fetchCharts().then(response => {   
  console.log(response.data)
})`

### CODE REVIEW

**Comment by ajhsu** [comment]
Hi @LeoLiu1209 , Thanks for your contribution!

By looking into your problem, I got few things to share:

1. In fact, we've designed a parameter that you can assign your territory code, on the second parameter of the constructor of `Api` class.
By doing so, you can fetch charts from other territories (JP, HK.. etc) as you expected:

```
// Set the territory to 'JP'
const api = new Api(accessToken, 'JP');
const result = await api.chartFetcher.fetchCharts();

// You will get charts from JP!
console.log(
  JSON.stringify(
    result.data
  )
);
```

2. Then I dug into the problem even more; I found that there is another issue that will make the territory value within ChartFetcher unchangeable. And I just create another PR (https://github.com/KKBOX/OpenAPI-JavaScript/pull/9) for it.

3. Considering about API consistency, I won't create a method (`setTerritory()`) only for `ChartFetcher`, but should create for all fetchers; That is, we should move your implementation into the `Fetcher` class.

**Comment by ghost** [comment]
I also found that issue [#9](https://github.com/KKBOX/OpenAPI-JavaScript/pull/9) when i dug into the code.
I was wonder why the territory value always assigned to 'TW', so i add a method to set for the constructor value.
At the end, thanks for responding for this PR.  
I am starting my side project with KKBOX Javascript SDK.
Thanks for KKBOX OpenAPI :100:

**Comment by ajhsu** [comment]
@LeoLiu1209 
Yeah, we've fixed the issue; You may now update to [`1.2.3`](https://www.npmjs.com/package/@kkbox/kkbox-js-sdk) to meet your requirement!

Back to your suggestion, would you like to help us to move `setTerritory` method into the `Fetcher` class? So that we can set the territory whenever we need, I think that would be handy.

By the way, we are also quite looking forward to your side-project; 
Please do let us know when it is released 👍

**Comment by ghost** [comment]
@ajhsu 
Following your suggestion, i already moved setTerritory() from `ChartFetcher` into `Fetcher ` class, so all fetchers could use it to set for Territory.
If the PR need to be revised or corrected, please let me know :hand:

**Comment by ajhsu** [comment]
@LeoLiu1209 
Could you please help me to rename the title, so that can meet what we've changed in this PR?
And that would be even better if you could merge multiple commits into single one via git rebase! (Since we have only one commit that actually making changes)

**Comment by ghost** [comment]
@ajhsu 
Hi. I just change the title of this PR in order to fit the changes and follow your suggestion to use git rebase to squash my commit into one!!!
If the PR need to be revised or corrected, i will try my best to make it more completely :muscle:

**Comment by ajhsu** [comment]
Thanks for your contributing! We're really looking forward to your side-project, seriously! 😄

**Pull request merged**
